apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-service
          image: client-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30003
  type: NodePort