apiVersion: apps/v1
kind: Deployment
metadata:
  name: technician-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technician
  template:
    metadata:
      labels:
        app: technician
    spec:
      containers:
        - name: technician-service
          image: technician-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: technician-service
spec:
  selector:
    app: technician
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30005
  type: NodePort